// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/tcs/automation/release/ui/home","exact":true,"parentId":"@@/global-layout","id":"1"},"2":{"path":"/home","redirect":"/tcs/automation/release/ui/home","exact":true,"parentId":"@@/global-layout","id":"2"},"3":{"path":"/tcs/automation/release/ui/home","exact":true,"title":"home.title","parentId":"@@/global-layout","id":"3"},"4":{"path":"/search","redirect":"/tcs/automation/release/ui/search/","exact":true,"parentId":"@@/global-layout","id":"4"},"5":{"path":"/tcs/automation/release/ui/search","exact":true,"title":"search.title","name":"search.title","parentId":"@@/global-layout","id":"5"},"6":{"path":"/create","redirect":"/tcs/automation/release/ui/create","exact":true,"parentId":"@@/global-layout","id":"6"},"7":{"path":"/tcs/automation/release/ui/create","exact":true,"title":"create","name":"create","parentId":"@@/global-layout","id":"7"},"8":{"path":"*","exact":true,"title":"NotFound","name":"NotFound","parentId":"@@/global-layout","id":"8"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': require( './EmptyRoute').default,
'2': require( './EmptyRoute').default,
'3': require('@/pages/home-page/index.tsx').default,
'4': require( './EmptyRoute').default,
'5': require('@/pages/search-page/index.tsx').default,
'6': require( './EmptyRoute').default,
'7': require('@/pages/create-page/index.tsx').default,
'8': require('@/pages/not-found/index.tsx').default,
'@@/global-layout': require('D:/learn-workshop/new2-umi4-max/src/layouts/index.tsx').default,
},
  };
}
