// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/tcs/automation/release/ui/home","exact":true,"parentId":"@@/global-layout","id":"1"},"2":{"path":"/home","redirect":"/tcs/automation/release/ui/home","exact":true,"parentId":"@@/global-layout","id":"2"},"3":{"path":"/tcs/automation/release/ui/home","exact":true,"title":"home.title","parentId":"@@/global-layout","id":"3"},"4":{"path":"/search","redirect":"/tcs/automation/release/ui/search/","exact":true,"parentId":"@@/global-layout","id":"4"},"5":{"path":"/tcs/automation/release/ui/search","exact":true,"title":"search.title","name":"search.title","parentId":"@@/global-layout","id":"5"},"6":{"path":"/create","redirect":"/tcs/automation/release/ui/create","exact":true,"parentId":"@@/global-layout","id":"6"},"7":{"path":"/tcs/automation/release/ui/create","exact":true,"title":"create","name":"create","parentId":"@@/global-layout","id":"7"},"8":{"path":"*","exact":true,"title":"NotFound","name":"NotFound","parentId":"@@/global-layout","id":"8"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import( './EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__home-page__index" */'@/pages/home-page/index.tsx')),
'4': React.lazy(() => import( './EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__search-page__index" */'@/pages/search-page/index.tsx')),
'6': React.lazy(() => import( './EmptyRoute')),
'7': React.lazy(() => import(/* webpackChunkName: "p__create-page__index" */'@/pages/create-page/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__not-found__index" */'@/pages/not-found/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'D:/learn-workshop/new2-umi4-max/src/layouts/index.tsx')),
},
  };
}
